99-Methods attributes have been changed
DefinitelyLD/KPP pull request #101
Opened 2022-07-04 13:39 UTC by StephanNazarkin

2022-07-04 13:46 UTC, vladimir-riabenko requested changes

2022-07-04 13:46 UTC, vladimir-riabenko commented on Messenger.Mapping/UnitOfWork.cs
> +        {
У тебя UoW в слое маппера

2022-07-04 13:46 UTC, vladimir-riabenko commented on Messenger/appsettings.json
> -    "Password": "",
.-.

2022-07-04 14:16 UTC, StephanNazarkin commented on Messenger/appsettings.json
> -    "Password": "",
Та пофиг, не?

2022-07-04 14:17 UTC, StephanNazarkin commented on Messenger.Mapping/UnitOfWork.cs
> +        {
Убрал

2022-07-06 10:27 UTC, vladimir-riabenko approved these changes

2022-07-06 10:49 UTC, AlexandrTsV requested changes

2022-07-06 10:49 UTC, AlexandrTsV commented on Messenger/appsettings.json
> +          "connectionString": "Server=(localdb)\\mssqllocaldb;Database=messenger;Trusted_Connection=True",
sensitive data

2022-07-06 10:55 UTC, StephanNazarkin commented on Messenger/appsettings.json
> +          "connectionString": "Server=(localdb)\\mssqllocaldb;Database=messenger;Trusted_Connection=True",
It's ok

2022-07-06 10:55 UTC, StephanNazarkin commented on Messenger/appsettings.json
> +          "connectionString": "Server=(localdb)\\mssqllocaldb;Database=messenger;Trusted_Connection=True",
So approve

2022-07-06 11:02 UTC, StephanNazarkin commented on Messenger/appsettings.json
> +          "connectionString": "Server=(localdb)\\mssqllocaldb;Database=messenger;Trusted_Connection=True",
Donw

2022-07-06 11:14 UTC, merged